#include <stdio.h>
#include <limits.h>
#include "ft_printf.h"

int		main(int ac, char **av)
{
	int		i;
	int		y;

	i = 0;
	y = 0;
//	ft_printf("%7884s", av[1]);
//	puts("");
//	printf("%7884s", av[1]);
//	i = ft_printf("%.5p", 0);
//	puts("");
// 	y = printf("%.5p", 0);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%X", 42);
//	puts("");
//	y = printf("%X", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%X", 42);
//	puts("");
//	y = printf("%X", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("{%010d}", 42);
//	puts("");
//	y = printf("{%010d}", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%.4o", 42);
//	puts("");
//	y = printf("%.4o", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%hd%hd", (short int)0, (short int)42);
//	puts("");
//	y = printf("%hd%hd", (short int)0, (short int)42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%hhd%hhd", 1, 42);
//	puts("");
//	y = printf("%hhd%hhd", 1, 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%o, %ho, %hho", -42, -42, -42);
//	puts("");
//	y = printf("%o, %ho, %hho", -42, -42, -42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%o", 42);
//	puts("");
//	y = printf("%o", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%.4s", "42");
//	puts("");
//	y = printf("%.4s", "42");
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%i", 42);
//	puts("");
//	y = printf("%i", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%.4d", 42);
//	puts("");
//	y = printf("%.4d", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%ld%ld", 0l, 42l);
//	puts("");
//	y = printf("%ld%ld", 0l, 42l);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%s", "abc");
//	puts("");
//	y = printf("%s", "abc");
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%.c", 0);
//	puts("");
//	y = printf("%.c", 0);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%d", 42);
//	puts("");
//	y = printf("%d", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("{%f}{%lf}{%Lf}", 1.42, 1.42, 1.42l);
//	puts("");
//	y = printf("{%f}{%lf}{%Lf}", 1.42, 1.42, 1.42l);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%hhd - %hhd", SHRT_MAX - 42, SHRT_MAX - 4200);
//	puts("");
//	y = printf("%hhd - %hhd", SHRT_MAX - 42, SHRT_MAX - 4200);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%c", 'c');
//	puts("");
//	y = printf("%c", 'c');
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("This is a simple test.");
//	puts("");
//	y = printf("This is a simple test.");
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("{%10d}", 42);
//	puts("");
//	y = printf("{%10d}", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%u", 42);
//	puts("");
//	y = printf("%u", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%s %d %p %% %x", "bonjour ", 42, &free, 42);
//	puts("");
//	y = printf("%s %d %p %% %x", "bonjour ", 42, &free, 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%p", &i);
//	puts("");
//	y = printf("%p", &i);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%#.o, %#.0o", 0, 0);
//	puts("");
//	y = printf("%#.o, %#.0o", 0, 0);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("{% +d}", 42);
//	puts("");
//	y = printf("{% +d}", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("s: %s, p: %p, d:%d", "a string", &i, 42);
//	puts("");
//	y = printf("s: %s, p: %p, d:%d", "a string", &i, 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("{%-10d}", 42);
//	puts("");
//	y = printf("{%-10d}", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%%");
//	puts("");
//	y = printf("%%");
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%lld%lld", 0ll, 42ll);
//	puts("");
//	y = printf("%lld%lld", 0ll, 42ll);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i  = ft_printf("% d", 9999);
//	puts("");
//	y = printf("% d", 9999);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%#o", 42);
//	puts("");
//	y = printf("%#o", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%x", 42);
//	puts("");
//	y = printf("%x", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("111%s333%s555", "222", "444");
//	puts("");
//	y = printf("111%s333%s555", "222", "444");
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%u", -42);
//	puts("");
//	y = printf("%u", -42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
//	i = ft_printf("%+d", 42);
//	puts("");
//	y = printf("%+d", 42);
//	printf("\nft_pf = %d\tpf = %d\n", i, y);
//	puts("");
	i = ft_printf("%.2147483649f|%2147483649f|%d\n", 1.0, 1.0, 7);
	y = printf("%.2147483649f|%2147483649f|%d\n", 1.0, 1.0, 7);
	printf("\nft_pf = %d\tpf = %d\n", i, y);

	return (0);
}
